import {useEffect,useRef,useState} from 'react';import uPlot from 'uplot';import 'uplot/dist/uPlot.min.css';import {samples,getPath,Data} from './store';
export type Line={key:string;label:string;color:string;scale?:number;warning?:number;critical?:number};
export function Chart({lines,period=300,height=240,source}:{lines:Line[];period?:number;height?:number;source?:Data[]}){
 const host=useRef<HTMLDivElement>(null);const plot=useRef<uPlot|null>(null);const [tip,setTip]=useState('');const [error,setError]=useState('');const key=JSON.stringify(lines);
 useEffect(()=>{if(!host.current)return;let disposed=false;let history:Data[]=[];let live:Data[]=samples.get();let abort=new AbortController();
 const alerts=lines.flatMap((l,i)=>[...(l.warning!=null?[{line:l,index:i,threshold:l.warning,color:'#dca350',label:'Высокий уровень'}]:[]),...(l.critical!=null?[{line:l,index:i,threshold:l.critical,color:'#e76571',label:'Пик нагрузки'}]:[])]);
 const chart=new uPlot({width:Math.max(100,host.current.clientWidth),height,series:[{label:'Время'},...lines.map(l=>({label:l.label,stroke:l.color,width:1.7,spanGaps:false})),...alerts.map(a=>({label:a.label,stroke:a.color,width:2.5,spanGaps:false,points:{show:true,size:4,stroke:a.color,fill:a.color}}))],scales:{x:{time:true}},legend:{show:false},cursor:{drag:{x:false,y:false}},axes:[{stroke:'#858a97',grid:{show:false},font:'11px -apple-system',size:34,values:(_u,vals)=>vals.map(v=>new Date(v*1000).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit',second:'2-digit'}))},{stroke:'#858a97',grid:{stroke:'rgba(130,138,155,.12)',width:1},font:'11px -apple-system',size:48}],hooks:{setCursor:[u=>{const i=u.cursor.idx;if(i==null){setTip('');return}const ts=u.data[0][i];setTip(new Date(ts*1000).toLocaleTimeString('ru-RU')+' · '+lines.map((l,n)=>`${l.label}: ${u.data[n+1][i]?.toFixed(1)??'—'}`).join(' · ')+alerts.map((a,j)=>{const peak=u.data[lines.length+1+j]?.[i];return a.threshold===a.line.critical&&peak!=null?` · пик ${a.line.label}: ${peak.toFixed(1)}`:''}).join(''))}]}},[[],...lines.map(()=>[]),...alerts.map(()=>[])] as uPlot.AlignedData,host.current);plot.current=chart;
 const draw=()=>{if(disposed||document.hidden)return;const end=Date.now()/1000;const points=new Map<number,Data>();if(source){source.forEach(v=>points.set(v.ts,v))}else{history.forEach(v=>points.set(v.ts,v));live.forEach(v=>points.set(v.ts,v))}const data=[...points.values()].filter(v=>v.ts>=end-period).sort((a,b)=>a.ts-b.ts);const read=(p:Data,l:Line)=>{const v=p.metrics?(typeof p.metrics[l.key]==='number'?p.metrics[l.key]:p.metrics[l.key]?.avg):getPath(p,l.key);return v==null?null:v/(l.scale||1)};chart.setData([data.map(v=>v.ts),...lines.map(l=>data.map(v=>read(v,l))),...alerts.map(a=>data.map(v=>{const peak=v.metrics?.[a.line.key]?.max;const n=peak==null?read(v,a.line):peak/(a.line.scale||1);return n!=null&&n>=a.threshold?n:null}))] as uPlot.AlignedData);if(!source)chart.setScale('x',{min:end-period,max:end});};
 const fetchHistory=()=>{if(source){draw();return}fetch(`/api/history?since=${Date.now()/1000-period}`,{signal:abort.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>{history=d;setError('');draw()}).catch(e=>{if(e.name!=='AbortError')setError('История недоступна')})};fetchHistory();const unsub=samples.sub(()=>{live=samples.get();draw()});const resize=new ResizeObserver(()=>{if(host.current)chart.setSize({width:Math.max(100,host.current.clientWidth),height})});resize.observe(host.current);const resume=()=>fetchHistory();window.addEventListener('monitor-resume',resume);const timer=setInterval(fetchHistory,60000);draw();return()=>{disposed=true;abort.abort();unsub();resize.disconnect();clearInterval(timer);window.removeEventListener('monitor-resume',resume);chart.destroy();plot.current=null};
 },[key,period,height,source]);
 return <div className="chart"><div ref={host}/><div className="chart-caption">{error||tip||'Наведите на график, чтобы увидеть точные значения'}</div><div className="legend">{lines.map(l=><span key={l.key}><i style={{background:l.color}}/>{l.label}</span>)}</div></div>
}
export function Spark({metric,color='#6bafdf'}:{metric:string;color?:string}){const path=useRef<SVGPathElement>(null);useEffect(()=>{const draw=()=>{const data=samples.get().slice(-60).map(v=>getPath(v,metric));const valid=data.filter((v):v is number=>v!==null);if(!valid.length)return;const max=Math.max(...valid,1),min=Math.min(...valid,0);let pen=false;let d='';data.forEach((v,i)=>{if(v===null){pen=false;return}d+=`${pen?'L':'M'}${i/Math.max(1,data.length-1)*180},${37-(v-min)/(max-min)*30} `;pen=true});path.current?.setAttribute('d',d)};draw();return samples.sub(draw)},[metric]);return <svg className="spark" viewBox="0 0 180 40" preserveAspectRatio="none" aria-hidden="true"><path ref={path} fill="none" stroke={color} strokeWidth="1.8" vectorEffect="non-scaling-stroke"/></svg>}
