import {useState} from 'react';import {Cpu,Thermometer,Activity,MemoryStick} from 'lucide-react';import {system,processes,useChannel,Data} from './store';import{Chart,Line}from'./Chart';
const GB=1024**3;const n=(v:any,suffix='',d=0)=>v==null?'—':Number(v).toFixed(d)+suffix;
const heat=(value:number|null,warn=75,red=90)=>value==null?'unknown':value>=red?'critical':value>=warn?'warning':'normal';
export function ChipMap({onSelect}:{onSelect:(id:string)=>void}){
 const s=useChannel(system),p=useChannel(processes),h=s.hardware||{},m=s.memory||{};const[mode,setMode]=useState('Состояние'),[selected,setSelected]=useState('cpu');
 const cpuT=h.temp?.cpu_temp_avg,gpuT=h.temp?.gpu_temp_avg;const cpuLoad=h.cpu_active_ratio==null?null:h.cpu_active_ratio*100,gpuLoad=h.gpu_active_ratio==null?null:h.gpu_active_ratio*100;const pressure=m.pressure==='critical'?'critical':m.pressure==='warning'?'warning':m.pressure==='normal'?'normal':'unknown';
 const level=(load:number|null,temp:number|null)=>mode==='Температура'?heat(temp,80,90):mode==='Нагрузка'?heat(load):heat(temp,80,90)==='critical'||heat(load)==='critical'?'critical':heat(temp,80,90)==='warning'||heat(load)==='warning'?'warning':heat(load);
 const activate=(key:string)=>({role:'button',tabIndex:0,'aria-label':`Показатели ${key==='cpu'?'CPU':key==='gpu'?'GPU':key==='memory'?'памяти':'Neural Engine'}`,'aria-pressed':selected===key,onClick:()=>setSelected(key),onKeyDown:(e:React.KeyboardEvent)=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(key)}}});
 const titles:Data={cpu:'CPU · 4 Performance + 4 Efficiency',gpu:'GPU · 10 ядер',memory:'Unified Memory',ane:'Neural Engine · 16 ядер'};
 const lines:Record<string,Line[]>={cpu:[{key:'cpu',label:'CPU, %',color:'#629cd6',warning:75,critical:90}],gpu:[{key:'hardware.gpu_active_ratio',label:'GPU, %',color:'#a18cd1',scale:.01,warning:80,critical:95}],memory:[{key:'memory.used',label:'RAM, ГиБ',color:'#a18cd1',scale:GB},{key:'memory.compressed',label:'Compressed, ГиБ',color:'#d7ac68',scale:GB},{key:'memory.swap',label:'Swap, ГиБ',color:'#cf7f84',scale:GB}],ane:[{key:'hardware.ane_power',label:'ANE, W',color:'#6fbaa0'}]};
 const tempLines:Record<string,Line[]>={cpu:[{key:'hardware.temp.cpu_temp_avg',label:'CPU, °C',color:'#d7ac68',warning:80,critical:90}],gpu:[{key:'hardware.temp.gpu_temp_avg',label:'GPU, °C',color:'#a18cd1',warning:80,critical:90}]};
 const current=selected==='cpu'?[["Загрузка CPU",n(s.cpu,'%')],["Средняя температура",n(cpuT,'°C',1)],["Мощность",n(h.cpu_power,' W',2)]]:selected==='gpu'?[["Активность GPU",n(gpuLoad,'%')],["Средняя температура",n(gpuT,'°C',1)],["Мощность",n(h.gpu_power,' W',2)]]:selected==='memory'?[["Используется",n(m.used==null?null:m.used/GB,' / '+n(m.total/GB,' ГиБ'),1)],["Memory pressure",({normal:'Нормальное',warning:'Повышенное',critical:'Критическое'}as Data)[m.pressure]||'Недоступно'],["Температура DRAM","Датчик недоступен"]]:[["Мощность",n(h.ane_power,' W',3)],["Загрузка, %","Датчик недоступен"],["Температура","Датчик недоступен"]];
 const top=[...p].filter(v=>v[selected==='memory'?'memory':'cpu']!=null).sort((a,b)=>(b[selected==='memory'?'memory':'cpu']||0)-(a[selected==='memory'?'memory':'cpu']||0)).slice(0,3);
 return <section className="panel chip-panel"><div className="panel-title"><div><h2>Внутри вашего Mac</h2><p className="chip-subtitle">Apple M3 · интерактивная карта нагрузки и температуры</p></div><div className="tabs chip-modes">{['Состояние','Нагрузка','Температура'].map(v=><button key={v} className={mode===v?'selected':''} onClick={()=>setMode(v)}>{v}</button>)}</div></div><div className="chip-layout"><div className="chip-visual"><svg viewBox="0 0 624 352" className="chip-svg" aria-label="Функциональная схема Apple M3, интерактивные блоки CPU GPU памяти и Neural Engine">
 <rect className="chip-package" x="12" y="30" width="596" height="308" rx="12"/><rect className="chip-die" x="24" y="42" width="412" height="282" rx="6"/><text className="chip-top-label" x="27" y="19">APPLE M3 · SoC</text><text className="chip-top-label" x="462" y="19">UNIFIED MEMORY</text>
 <path className="chip-bus" d="M184 131H198M248 118H264M248 230H264M140 243V258M224 250V258M436 111H459M436 254H459"/>
 <g {...activate('cpu')} className={`chip-block ${level(cpuLoad,cpuT)} ${selected==='cpu'?'chosen':''}`}><rect x="36" y="54" width="148" height="190" rx="5"/><text className="block-title" x="48" y="76">CPU</text><text className="block-temp" x="172" y="76" textAnchor="end">{n(cpuT,'°C')}</text><text className="cluster-label" x="48" y="96">4 PERFORMANCE CORES</text>{(h.pcpu_cores||Array(4).fill({active_ratio:null})).map((c:Data,i:number)=><g key={i} className={'core-cell '+(mode==='Температура'?'unknown':heat(c.active_ratio==null?null:c.active_ratio*100))}><rect x={48+i%2*62} y={104+Math.floor(i/2)*29} width="57" height="24" rx="3"/><text x={53+i%2*62} y={120+Math.floor(i/2)*29}>P{i+1}<tspan x={100+i%2*62} textAnchor="end">{n(c.active_ratio==null?null:c.active_ratio*100,'%')}</tspan></text></g>)}<text className="cluster-label" x="48" y="179">4 EFFICIENCY CORES</text>{(h.ecpu_cores||Array(4).fill({active_ratio:null})).map((c:Data,i:number)=><g key={i} className={'core-cell '+(mode==='Температура'?'unknown':heat(c.active_ratio==null?null:c.active_ratio*100))}><rect x={48+i%2*62} y={187+Math.floor(i/2)*23} width="57" height="19" rx="2"/><text x={53+i%2*62} y={200+Math.floor(i/2)*23}>E{i+1}<tspan x={100+i%2*62} textAnchor="end">{n(c.active_ratio==null?null:c.active_ratio*100,'%')}</tspan></text></g>)}</g>
 <g className="chip-passive"><rect x="198" y="54" width="50" height="190" rx="4"/><text x="223" y="122" textAnchor="middle">SYSTEM</text><text x="223" y="137" textAnchor="middle">FABRIC</text><path className="fabric-lines" d="M214 65V98M223 65V98M232 65V98M214 165V229M223 165V229M232 165V229"/></g>
 <g {...activate('gpu')} className={`chip-block ${level(gpuLoad,gpuT)} ${selected==='gpu'?'chosen':''}`}><rect x="264" y="54" width="160" height="129" rx="5"/><text className="block-title" x="277" y="76">GPU</text><text className="block-temp" x="410" y="76" textAnchor="end">{n(gpuT,'°C')}</text><text className="chip-big" x="277" y="116">{n(gpuLoad,'%')}</text><text className="cluster-label" x="277" y="137">10 ЯДЕР · СУММАРНО</text><rect className="usage-track" x="277" y="149" width="133" height="9" rx="2"/><rect className="usage-fill" x="277" y="149" width={Math.max(0,Math.min(133,(gpuLoad||0)/100*133))} height="9" rx="2"/></g>
 <g {...activate('ane')} className={`chip-block ${mode==='Температура'||h.ane_power==null?'unknown':'normal'} ${selected==='ane'?'chosen':''}`}><rect x="264" y="196" width="160" height="116" rx="5"/><text className="block-title" x="277" y="218">NEURAL ENGINE</text><text className="chip-big small" x="277" y="250">{h.ane_power==null?'—':h.ane_power>0&&h.ane_power<0.01?'< 0.01 W':n(h.ane_power,' W',2)}</text><text className="cluster-label" x="277" y="271">16 ЯДЕР · МОЩНОСТЬ</text><text className="cluster-label" x="277" y="293">{mode==='Температура'?'ТЕМПЕРАТУРА НЕДОСТУПНА':'АНАЛИТИКА ML / AI'}</text></g>
 <g className="chip-passive"><rect x="36" y="258" width="212" height="54" rx="4"/><text className="block-title" x="49" y="279">SYSTEM CACHE</text><text className="cluster-label" x="49" y="298">ДАТЧИКИ ЗАГРУЗКИ НЕДОСТУПНЫ</text></g>
 <g {...activate('memory')} className={`chip-block ${mode==='Температура'?'unknown':pressure} ${selected==='memory'?'chosen':''}`}><rect x="459" y="54" width="136" height="258" rx="5"/><text className="block-title" x="472" y="77">DRAM</text><text className="cluster-label" x="472" y="95">ОБЩАЯ ПАМЯТЬ</text><text className="chip-big small" x="472" y="126">{n(m.used==null?null:m.used/GB,' ГиБ',1)}</text><text className="cluster-label" x="472" y="144">ИЗ {n(m.total==null?null:m.total/GB,' ГиБ')}</text>{Array.from({length:8},(_,i)=><rect className={mode==='Температура'?'usage-track':(m.used/m.total*8>i?'usage-fill':'usage-track')} key={i} x={472+i%4*27} y={159+Math.floor(i/4)*30} width="23" height="25" rx="2"/>)}<text className="cluster-label" x="472" y="237">MEMORY PRESSURE</text><text className="memory-state" x="472" y="254">{({normal:'НОРМА',warning:'ПОВЫШЕНО',critical:'КРИТИЧЕСКОЕ'}as Data)[m.pressure]||'НЕДОСТУПНО'}</text><text className="cluster-label" x="472" y="281">ТЕМПЕРАТУРА</text><text className="cluster-label" x="472" y="295">ДАТЧИК НЕДОСТУПЕН</text></g>
 </svg><div className="chip-key"><span><i className="map-normal"/>Обычный уровень</span><span><i className="map-warning"/>Высокий</span><span><i className="map-critical"/>Пиковый / критический</span><span><i className="map-unknown"/>Нет датчика</span></div><p className="chip-disclaimer">Функциональная схема, не физический план кристалла. Температура CPU/GPU общая; отдельных температур ядер и DRAM нет. Цвет памяти — состояние pressure macOS.</p></div><div className="chip-inspector"><div className="chip-inspector-title"><Cpu size={16}/><h3>{titles[selected]}</h3></div><dl className="stat-list">{current.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><Chart lines={mode==='Температура'&&tempLines[selected]?tempLines[selected]:lines[selected]} period={300} height={155}/>{(selected==='cpu'||selected==='memory')&&<div className="chip-consumers"><span className="eyebrow">{selected==='memory'?'ГЛАВНЫЕ ПОТРЕБИТЕЛИ ПАМЯТИ':'ГЛАВНЫЕ ПОТРЕБИТЕЛИ CPU'}</span>{top.map(v=><button key={v.id} onClick={()=>onSelect(v.id)}><span>{v.label}</span><strong>{selected==='memory'?n(v.memory/GB,' ГиБ',2):n(v.cpu,'%',1)}</strong></button>)}</div>}{selected==='gpu'&&<p className="fine-print">Показана общая загрузка GPU. Атрибуция GPU по процессам недоступна.</p>}{selected==='ane'&&<p className="fine-print">Показана мощность Neural Engine за интервал измерения, не процент загрузки. 0 W означает, что счётчик не зарегистрировал энергию в этом интервале; «—» — счётчик недоступен. ANE ускоряет совместимые локальные ML-модели и не снимает обычную нагрузку CPU.</p>}</div></div></section>
}
