import React,{useEffect,useRef,useState} from 'react';
import {Activity,HardDrive,Container,MemoryStick,Search,X,ArrowRight,ChevronRight,ChevronLeft,ScanLine,Loader2,History,Info,Lock,ShieldCheck,Clock,Layers,Trash2,Square,CheckCircle2,AlertTriangle,Folder,FileText} from 'lucide-react';
import {system,processes,connection,useChannel,Data} from './store';
import './management.css';
import {DiskCapacity} from './DiskCapacity';
export type ManagementPage='Накопитель'|'Docker'|'Процессы'|'Освободить ресурсы';
import {formatBytes as size} from './units';
const pct=(n:unknown)=>typeof n==='number'?`${n.toFixed(1)}%`:'—';
const pressure:Record<string,string>={normal:'Нормальное',warning:'Повышенное',critical:'Критическое',unavailable:'Нет данных'};
const colors=['#6f9ecd','#a18bc8','#68ada6','#c2a170','#b78392','#6886b5','#9eac85','#8b93ac'];
const categoryColor=(name:string)=>colors[Math.abs([...name].reduce((n,c)=>(n*31+c.charCodeAt(0))|0,0))%colors.length];
function StorageMap({categories,scanning,select}:{categories:Data[];scanning:boolean;select:(path:string)=>void}){
 const state=(c:Data)=>!c.complete&&scanning?'Сканируется':c.partial?'Частично':'';
 return <><div className="ux-storage-treemap" aria-label="Соотношение размеров изученных папок">{[0,1,2].map(col=>{const tiles=categories.filter((c,i)=>i%3===col&&c.size>0);if(!tiles.length)return null;return <div key={col} className="ux-storage-column" style={{flex:tiles.reduce((n,c)=>n+c.size,0)}}>{tiles.map(c=><button key={c.path} className="ux-storage-tile" style={{'--tile':categoryColor(c.name),flex:c.size} as React.CSSProperties} title={`${c.name} · ${size(c.size)}${state(c)?' · '+state(c):''}`} aria-label={`Открыть ${c.name}, ${size(c.size)}`} onClick={()=>select(c.path)}><div className="ux-tile-content"><strong>{c.name}</strong><b>{size(c.size)}</b>{state(c)&&<small>{state(c)}</small>}</div></button>)}</div>})}</div><div className="ux-storage-legend">{categories.map(c=><button key={c.path} onClick={()=>select(c.path)}><i style={{background:categoryColor(c.name)}}/><span><strong>{c.name}</strong><small>{state(c)||'Просканировано'}</small></span><b>{c.size===0&&!c.complete?'…':size(c.size)}</b><ChevronRight size={13}/></button>)}</div><p className="ux-map-caption">Площадь блоков соответствует размерам изученных папок. Все категории доступны в списке.</p></>
}
async function api(path:string,body?:Data){let headers:Record<string,string>={};if(body){const session=await api('/api/manage/session');headers={'Content-Type':'application/json','X-Sysmo-Token':session.token};}const r=await fetch(path,{method:body?'POST':'GET',headers,body:body?JSON.stringify(body):undefined,cache:'no-store'});let d;try{d=await r.json()}catch{throw new Error('Агент не вернул данные. Проверьте соединение и версию агента.')}if(!r.ok)throw new Error(d.error||`Ошибка ${r.status}`);return d;}
function useRemote(path:string,interval=15000){const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[revision,refresh]=useState(0);useEffect(()=>{let alive=true;let timer:ReturnType<typeof setTimeout>;const load=async()=>{try{const d=await api(path);if(alive){setData(d);setError('')}}catch(e){if(alive)setError(String((e as Error).message))}finally{if(alive)timer=setTimeout(load,interval)}};load();return()=>{alive=false;clearTimeout(timer)}},[path,interval,revision]);return {data,error,refresh:()=>refresh(v=>v+1)}}
function Dialog({title,close,children,busy=false}:{title:string;close:()=>void;children:React.ReactNode;busy?:boolean}){const ref=useRef<HTMLDivElement>(null),closeRef=useRef(close);closeRef.current=close;useEffect(()=>{const old=document.activeElement as HTMLElement,overflow=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.focus();const listener=(e:KeyboardEvent)=>{if(e.key==='Escape')closeRef.current();if(e.key==='Tab'){const els=Array.from(ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),a[href]')||[]);const first=els[0],last=els.at(-1);if(!first){e.preventDefault();return}if(e.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){e.preventDefault();last?.focus()}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===ref.current)){e.preventDefault();first.focus()}}};document.addEventListener('keydown',listener);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',listener);old?.focus()}},[]);return <div className="ux-modal-layer"><div className="ux-dialog" ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-label={title}><div className="ux-dialog-heading"><h2>{title}</h2><button className="ux-icon" aria-label="Закрыть окно" disabled={busy} onClick={close}><X size={18}/></button></div>{children}</div></div>}
function Kpi({label,value,note,icon:Icon,tone=''}:{label:string;value:string;note:string;icon:typeof Activity;tone?:string}){return <div className={`ux-kpi ${tone}`}><div><Icon size={17}/>{label}</div><strong>{value}</strong><small>{note}</small></div>}
function Empty({title,text}:{title:string;text:string}){return <div className="ux-empty"><Info size={28}/><h3>{title}</h3><p>{text}</p></div>}
function SearchBox({value,onChange,placeholder}:{value:string;onChange:(v:string)=>void;placeholder:string}){return <label className="ux-search"><Search size={16}/><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/>{value&&<button aria-label="Очистить поиск" onClick={()=>onChange('')}><X size={14}/></button>}</label>}
function Tabs({values,value,set}:{values:string[];value:string;set:(v:string)=>void}){return <div className="ux-tabs">{values.map(v=><button key={v} aria-pressed={v===value} className={v===value?'selected':''} onClick={()=>set(v)}>{v}</button>)}</div>}
type Propose=(action:string,id:string)=>void;
export function Management({page,onNavigate,onProcess}:{page:ManagementPage;onNavigate:(v:ManagementPage)=>void;onProcess:(id:string)=>void}){
 const s=useChannel(system),rows=useChannel(processes),live=useChannel(connection)==='connected';const [plan,setPlan]=useState<Data|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[journal,setJournal]=useState<Data[]|null>(null),[revision,setRevision]=useState(0);
 const propose:Propose=async(action,id)=>{if(busy)return;setBusy(true);setError('');try{setPlan(await api('/api/manage/plan',{action,id}))}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const execute=async()=>{if(!plan||busy)return;setBusy(true);setError('');try{const result=await api('/api/manage/execute',{plan:plan.plan});setMessage(result.message);setPlan(null);setRevision(v=>v+1)}catch(e){setError((e as Error).message);setPlan(null)}finally{setBusy(false)}};
 const headings:Record<ManagementPage,[string,string]>={'Накопитель':['Место для нового.','Реальная ёмкость SSD и размеры доступных папок.'],'Docker':['Контейнеры под контролем.','Данные локального Docker. Любое действие — с проверкой и подтверждением.'],'Процессы':['Что занимает ваш Mac.','Живая нагрузка и завершение выбранного процесса по его PID.'],'Освободить ресурсы':['Больше пространства для работы.','Память macOS и процессы, которые вы можете завершить.']};
 return <div className="studio embedded"><div className="ux-management-top"><span className="ux-label"><ShieldCheck size={14}/>Локальные данные · действия с подтверждением</span><button className="ux-history" onClick={async()=>{try{setJournal((await api('/api/manage/session')).journal)}catch(e){setError((e as Error).message)}}}><History size={16}/>Журнал действий</button></div><div className="ux-page-title"><span className="ux-eyebrow">SYSTEM MONITOR / {page.toLocaleUpperCase()}</span><h1>{headings[page][0]}</h1><p>{headings[page][1]}</p></div>
 {!live&&<div className="ux-inline-note"><AlertTriangle size={18}/>Связь с агентом потеряна. Показатели могут быть устаревшими; управление недоступно.</div>}
 {error&&<div role="alert" className="ux-live-alert"><AlertTriangle size={18}/><span>{error}</span><button aria-label="Закрыть ошибку" onClick={()=>setError('')}><X size={16}/></button></div>}
 {message&&<div role="status" className="ux-result"><CheckCircle2 size={22}/><p>{message}</p><button className="ux-icon" aria-label="Скрыть результат" onClick={()=>setMessage('')}><X size={16}/></button></div>}
 {page==='Накопитель'?<Storage s={s} navigate={onNavigate}/>:page==='Docker'?<DockerView revision={revision} propose={propose} disabled={!live||busy}/>:<ProcessView key={page} rows={rows} s={s} resources={page==='Освободить ресурсы'} onProcess={onProcess} propose={propose} disabled={!live||busy} navigate={onNavigate}/>}
 {plan&&<Dialog title={plan.action==='process.terminate'?'Завершить процесс?':plan.action==='container.remove'?'Удалить остановленный контейнер?':'Остановить контейнер?'} busy={busy} close={()=>!busy&&setPlan(null)}><div className="ux-dialog-symbol"><AlertTriangle size={24}/></div><p>{plan.action==='process.terminate'?'Процесс получит SIGTERM. Несохранённая работа может быть потеряна. Дочерние процессы отдельно не завершаются.':plan.action==='container.remove'?'Будет удалён только этот контейнер и его записываемый слой. Файлы внутри слоя будут потеряны. Тома, bind-mount папки и образы сохранятся.':'Сервис станет недоступен. Docker запросит завершение и через 10 секунд может принудительно остановить контейнер.'}</p><div className="ux-plan-list"><div><strong>{plan.target.name||plan.target.Name?.replace(/^\//,'')}</strong></div><div><span>{plan.action==='process.terminate'?`PID ${plan.target.pid}`:plan.id}</span></div>{plan.target.executable&&<div><span>{plan.target.executable}</span></div>}{plan.target.Mounts?.map((m:Data,i:number)=><div key={i}><ShieldCheck size={16}/><span>Сохраняется: {m.Name||m.Source} → {m.Destination}</span></div>)}</div><div className="ux-inline-note"><Clock size={16}/>План действует 90 секунд. Перед действием агент повторно проверит объект.</div><div className="ux-dialog-actions"><button className="ux-button" disabled={busy} onClick={()=>setPlan(null)}>Отмена</button><button className="ux-button danger" disabled={busy||!live} onClick={execute}>{busy?<><Loader2 size={15} className="ux-spin"/>Выполняем…</>:'Подтвердить'}</button></div></Dialog>}
 {journal&&<Dialog title="Журнал действий" close={()=>setJournal(null)}>{journal.length?<div className="ux-journal">{journal.map((e,i)=><article key={i}>{e.ok?<CheckCircle2 size={18}/>:<AlertTriangle size={18}/>}<div><b>{e.action} · {e.id}</b><p>{e.detail}</p></div><time>{new Date(e.time*1000).toLocaleTimeString('ru-RU')}</time></article>)}</div>:<Empty title="Действий пока нет" text="Здесь показаны операции за текущий запуск агента. Постоянный журнал сохраняется в SQLite."/>}</Dialog>}
 </div>
}
function Storage({s,navigate}:{s:Data;navigate:(p:ManagementPage)=>void}){
 const remote=useRemote('/api/manage/storage',2000);const [selected,setSelected]=useState<string|null>(null),[tab,setTab]=useState('Категории'),[query,setQuery]=useState(''),[error,setError]=useState('');const d=remote.data,scanning=d?.status==='scanning';const categories:Data[]=d?.categories||[],files:Data[]=d?.files||[];const layout=s.disk_layout,layoutFresh=layout?.ts&&Date.now()/1000-layout.ts<180,layoutAvailable=layoutFresh&&['available','partial'].includes(layout?.status);const total=layoutAvailable?layout.container_total:s.disk?.total,free=layoutAvailable?layout.free:s.disk?.free,used=typeof total==='number'&&typeof free==='number'?total-free:null;const scanned=categories.reduce((a,c)=>a+c.size,0);const current=categories.find(c=>c.path===selected);
 const act=async(cancel=false)=>{try{setError('');await api(`/api/manage/storage/${cancel?'cancel':'start'}`,{});remote.refresh()}catch(e){setError((e as Error).message)}};
 const status:Record<string,string>={idle:'Ещё не сканировали',scanning:'Сканирование',complete:'Сканирование завершено',partial:'Частичный результат',cancelled:'Сканирование остановлено'};
 return <><div className="ux-kpis"><Kpi icon={HardDrive} label="Физическая ёмкость SSD" value={size(layoutAvailable?layout.physical_total:null)} note={`Основной APFS: ${size(total)}`}/><Kpi icon={Layers} label="Занято в APFS" value={size(used)} note="Без резерва других разделов"/><Kpi icon={Layers} label="Доступно" value={size(free)} note="Свободное место по данным macOS" tone="green"/><Kpi icon={Folder} label="В изученных папках ≈" value={categories.length?size(scanned):'—'} note="Выделенные блоки, без повторов hard links"/></div>
 {(error||remote.error)&&<div role="alert" className="ux-live-alert">{error||remote.error}</div>}
 <div className="ux-two-col"><section className="ux-card"><div className="ux-card-head"><div><h2>Что занимает место</h2><p>Весь SSD и доступные папки тома данных · только чтение</p></div><button className="ux-button" onClick={()=>act(scanning)}>{scanning?<Square size={14}/>:<ScanLine size={15}/>} {scanning?'Остановить':'Сканировать'}</button></div><DiskCapacity layout={layout} disk={s.disk}/>
 {scanning&&<div className="ux-inline-note"><Loader2 className="ux-spin" size={16}/>Обход папок в фоне · просмотрено {(d?.visited||0).toLocaleString('ru-RU')} объектов</div>}
 {layoutAvailable&&categories.length>0&&<div className="ux-card-foot"><Info size={14}/>{scanned<=layout.data_volume?`В томе данных пока не разложено по папкам ≈ ${size(layout.data_volume-scanned)}. Сюда входят недоступные области, снимки и незавершённый обход.`:"Размеры папок могут пересекаться из-за APFS clones или отличаться по времени измерения. Их сумма не подменяет физическую занятость."}</div>}
 {categories.length?<StorageMap categories={categories} scanning={scanning} select={path=>{setSelected(path);setTab('Категории');setQuery('')}}/>:<Empty title={scanning?'Собираем карту папок':'Карта накопителя'} text="Обход выполняется в фоне. Читаются только метаданные, файлы не открываются и не удаляются."/>}
 <div className="ux-card-foot"><Info size={14}/>{status[d?.status||'idle']}{d?.errors?` · пропущено / недоступно: ${d.errors}`:''}. Фоновый обход всех категорий · автоматическое обновление раз в 6 часов.</div></section>
 <aside className="ux-card ux-insight"><span className="ux-eyebrow">КАК ЧИТАТЬ КАРТУ</span><div className="ux-insight-icon"><HardDrive size={25}/></div><h2>Размер — с контекстом.</h2><p>Верхняя шкала охватывает весь SSD: данные, macOS, swap, служебные тома, резерв и свободное место. Карта ниже показывает размеры прочитанных папок, включая доступные системные области и других пользователей.</p><p>Закрытые macOS папки и снимки APFS нельзя полностью разложить по файлам. Клоны могут разделять блоки: сумма папок — оценка, а не обещание освобождения места.</p><button className="ux-button primary" onClick={()=>navigate('Docker')}>Хранилище Docker <ArrowRight size={16}/></button><small>Docker.raw уже входит в данные SSD. Объекты Docker внутри него не прибавляются к общему размеру.</small></aside></div>
 <section className="ux-card"><div className="ux-table-toolbar"><Tabs values={['Категории','Большие файлы']} value={tab} set={v=>{setTab(v);setSelected(null);setQuery('')}}/><SearchBox value={query} onChange={setQuery} placeholder="Найти папку или файл"/></div>{current&&tab==='Категории'&&<button className="ux-back" onClick={()=>setSelected(null)}><ChevronLeft size={15}/>Все категории <ChevronRight size={14}/>{current.name}</button>}<div className="ux-table-scroll"><table className="ux-table"><thead><tr><th>{tab==='Большие файлы'?'Файл':current?'Папка / файл':'Категория'}</th><th>На диске ≈</th><th>Информация</th></tr></thead><tbody>{(tab==='Большие файлы'?files:current?.items||categories).filter((c:Data)=>c.name.toLowerCase().includes(query.toLowerCase())).map((c:Data,i:number)=><tr key={c.path||c.name}><td><button className="ux-name" disabled={tab==='Большие файлы'||!!current} onClick={()=>setSelected(c.path)}>{tab==='Большие файлы'?<FileText size={18}/>:<Folder size={18} color={colors[i%colors.length]}/>}<span><b>{c.name}</b><small>{c.path||current?.path}</small></span></button></td><td>{size(c.size)}</td><td className="ux-muted">{tab==='Большие файлы'?`Логический размер: ${size(c.logical)}`:c.partial?'Частичный размер':'Только просмотр'}</td></tr>)}</tbody></table></div>{!(tab==='Большие файлы'?files:current?.items||categories).some((c:Data)=>c.name.toLowerCase().includes(query.toLowerCase()))&&<Empty title="Нет результатов" text="Измените поиск или запустите сканирование."/>}<div className="ux-card-foot"><Info size={14}/>До 50 крупнейших файлов среди просмотренных, от 10 MB. Ссылки не обходятся, другие тома не сканируются.</div></section></>
}
function dockerRows(d:Data,tab:string):Data[]{
 if(tab==='Контейнеры')return (d.containers||[]).map((c:Data)=>({id:c.Id,name:c.Names?.[0]?.replace(/^\//,'')||c.Id.slice(0,12),detail:c.Image,size:c.SizeRw,state:c.State,mounts:c.Mounts||[],days:c.FinishedAt&&!c.FinishedAt.startsWith('0001')?Math.max(0,Math.floor((Date.now()-Date.parse(c.FinishedAt))/86400000)):null,removable:['exited','created'].includes(c.State)&&!c.Managed,stoppable:c.State==='running'&&!c.Managed}));
 if(tab==='Образы')return(d.images||[]).map((i:Data)=>({id:i.Id,name:i.RepoTags?.join(', ')||i.Id.slice(7,19),detail:`Контейнеров: ${i.Containers??'—'} · общие слои: ${size(i.SharedSize)}`,size:i.Size,state:i.Containers>0?'Используется':'Без контейнеров',days:null}));
 if(tab==='Тома')return(d.volumes||[]).map((v:Data)=>({id:v.Name,name:v.Name,detail:`Драйвер: ${v.Driver} · ссылок: ${v.UsageData?.RefCount??'—'}`,size:v.UsageData?.Size,state:'Защищён',days:null}));
 return(d.cache||[]).map((c:Data)=>({id:c.ID,name:c.Description||c.ID,detail:`BuildKit · ${c.Type||'слой'}`,size:c.Size,state:c.InUse?'Используется':'Кэш',days:c.LastUsedAt?Math.max(0,Math.floor((Date.now()-Date.parse(c.LastUsedAt))/86400000)):null}));
}
function DockerView({revision,propose,disabled}:{revision:number;propose:Propose;disabled:boolean}){
 const remote=useRemote('/api/manage/docker',60000);const priorRevision=useRef(revision);useEffect(()=>{if(priorRevision.current!==revision){priorRevision.current=revision;remote.refresh()}},[revision]);const [tab,setTab]=useState('Контейнеры'),[query,setQuery]=useState(''),[filter,setFilter]=useState('Все'),[detail,setDetail]=useState<Data|null>(null);const d=remote.data||{},all=dockerRows(d,tab),rows=all.filter(c=>c.name.toLowerCase().includes(query.toLowerCase())&&(filter==='Все'||filter==='Остановлены'&&c.removable||filter==='Старше 30 дней'&&c.days!==null&&c.days>30));const containers=d.containers||[];const valid=!disabled&&!remote.error&&!!remote.data;
 return <><div className="ux-kpis"><Kpi icon={HardDrive} label="Docker.raw на SSD" value={size(d.desktop_disk?.allocated)} note={d.desktop_disk?'Фактически выделенные блоки':'Стандартный путь недоступен / изменён'}/><Kpi icon={Layers} label="Лимит виртуального диска" value={size(d.desktop_disk?.limit)} note="Не равно занятому месту на Mac"/><Kpi icon={Activity} label="Работают сейчас" value={remote.data?String(containers.filter((c:Data)=>c.State==='running').length):'—'} note="Контейнеров локального движка"/><Kpi icon={Container} label="Образы · общие слои" value={size(d.layers_size)} note="Учёт Docker внутри виртуальной машины"/></div><section className="ux-banner"><div className="ux-banner-icon"><ShieldCheck size={24}/></div><div><h2>Данные остаются под защитой.</h2><p>Удаляется только выбранный остановленный контейнер, через Docker. Тома, образы, кэш и папки Mac доступны только для просмотра.</p></div></section>
 {remote.error&&<div role="alert" className="ux-live-alert"><AlertTriangle size={18}/><span>Docker недоступен: {remote.error}. Последние данные могут быть устаревшими.</span><button className="ux-button" onClick={remote.refresh}>Повторить</button></div>}
 <section className="ux-card"><div className="ux-table-toolbar"><Tabs values={['Контейнеры','Образы','Тома','Кэш сборки']} value={tab} set={v=>{setTab(v);setFilter('Все')}}/><button className="ux-button" onClick={remote.refresh}>Обновить</button></div><div className="ux-filter-toolbar"><SearchBox value={query} onChange={setQuery} placeholder="Найти объект Docker"/><select aria-label="Фильтр Docker" value={filter} onChange={e=>setFilter(e.target.value)}><option>Все</option>{tab==='Контейнеры'&&<option>Остановлены</option>}{['Контейнеры','Кэш сборки'].includes(tab)&&<option>Старше 30 дней</option>}</select></div>{!remote.data&&!remote.error?<Empty title="Читаем хранилище Docker" text="Движку может понадобиться время для подсчёта размеров."/>:!rows.length?<Empty title="Объектов не найдено" text="В этой категории нет доступных объектов с выбранными условиями."/>:<div className="ux-table-scroll"><table className="ux-table"><thead><tr><th>Объект</th><th>Состояние</th><th>{tab==='Контейнеры'?'Записываемый слой':'Размер'}</th><th>Без работы</th><th/></tr></thead><tbody>{rows.map(c=><tr key={c.id}><td><button className="ux-name" onClick={()=>setDetail(c)}><Container size={18}/><span><b>{c.name}</b><small>{c.detail}</small></span></button></td><td><span className={`ux-status ${c.state==='running'?'green':''}`}>{c.state}</span></td><td>{size(c.size)}</td><td>{Number.isFinite(c.days)&&c.days!==null?`${c.days} дн.`:'—'}</td><td>{c.removable?<button className="ux-button danger" disabled={!valid} onClick={()=>propose('container.remove',c.id)}><Trash2 size={14}/>Удалить</button>:c.stoppable?<button className="ux-button" disabled={!valid} onClick={()=>propose('container.stop',c.id)}><Square size={13}/>Остановить</button>:<span className="ux-label"><Lock size={13}/>Просмотр</span>}</td></tr>)}</tbody></table></div>}<div className="ux-card-foot"><Info size={14}/>{tab==='Контейнеры'?'Возраст — с момента остановки. Размер слоя не включает тома и не обещает такое же освобождение SSD.':tab==='Кэш сборки'?'Возраст — с последнего использования, когда движок сообщает эту дату.':'Размеры могут включать общие данные. Не суммируйте их как освобождаемое место.'}</div></section>
 <div className="ux-note-grid"><div className="ux-card ux-note"><ShieldCheck size={21}/><h3>Проверка перед действием</h3><p>Агент повторно проверяет ID, состояние, настройки, подключения и тот же движок Docker. При изменении объекта операция отменяется.</p></div><div className="ux-card ux-note"><HardDrive size={21}/><h3>Место на Mac обновится отдельно</h3><p>Docker управляет освобождением блоков виртуального диска. Монитор не удаляет Docker.raw и не уменьшает его лимит.</p></div></div>
 {detail&&<Dialog title={detail.name} close={()=>setDetail(null)}><p>{detail.detail}</p><dl className="ux-details"><div><dt>ID</dt><dd className="ux-break">{detail.id}</dd></div><div><dt>Размер</dt><dd>{size(detail.size)}</dd></div><div><dt>Состояние</dt><dd>{detail.state}</dd></div></dl>{detail.mounts?.map((m:Data,i:number)=><div key={i} className="ux-inline-note"><ShieldCheck size={16}/><span>Сохраняется: {m.Name||m.Source} → {m.Destination}</span></div>)}<div className="ux-dialog-actions"><button className="ux-button" onClick={()=>setDetail(null)}>Закрыть</button></div></Dialog>}</>
}
function ProcessView({rows,s,resources,onProcess,propose,disabled,navigate}:{rows:Data[];s:Data;resources:boolean;onProcess:(id:string)=>void;propose:Propose;disabled:boolean;navigate:(p:ManagementPage)=>void}){
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('Все'),[sort,setSort]=useState('memory'),[limit,setLimit]=useState(60);const memory=s.memory||{};const protectedProcess=(p:Data)=>!p.manage_allowed;
 const filtered=rows.filter(p=>(!resources||!protectedProcess(p))&&[p.name,p.group,p.pid,p.project].join(' ').toLowerCase().includes(query.toLowerCase())&&(filter==='Все'||filter==='Приложения'&&p.application||filter==='Разработка'&&p.development||filter==='Доступны к завершению'&&!protectedProcess(p))).sort((a,b)=>(b[sort]||0)-(a[sort]||0));
 return <>{resources?<section className="ux-memory-hero"><div className="ux-memory-copy"><span className="ux-eyebrow">ДАВЛЕНИЕ НА ПАМЯТЬ</span><h2>{pressure[memory.pressure]||'Ожидаем данные'}</h2><p>Завершайте только процессы, работа которых вам сейчас не нужна.</p><span className="ux-label"><Activity size={14}/>Измерения macOS в реальном времени</span></div><div className="ux-memory-visual"><svg viewBox="0 0 180 180" role="img" aria-label={`Память: ${size(memory.used)} из ${size(memory.total)}`}><circle cx="90" cy="90" r="76" fill="none" stroke="var(--border)" strokeWidth="8"/><circle cx="90" cy="90" r="76" fill="none" stroke={memory.pressure==='critical'?'var(--red)':memory.pressure==='warning'?'var(--warning)':'var(--accent)'} strokeWidth="8" strokeLinecap="round" pathLength="100" strokeDasharray={`${Math.min(100,Math.max(0,memory.total?memory.used/memory.total*100:0))} 100`} transform="rotate(-90 90 90)"/></svg><div><strong>{size(memory.used)}</strong><span>из {size(memory.total)}</span></div></div><dl><div><dt>Сжатая память</dt><dd>{size(memory.compressed)}</dd></div><div><dt>Swap</dt><dd>{size(memory.swap)}</dd></div><div><dt>Доступно, оценка</dt><dd>{size(memory.available)}</dd></div></dl></section>:<div className="ux-kpis"><Kpi icon={Activity} label="Процессов" value={String(rows.length)} note="Каждая строка — один PID"/><Kpi icon={MemoryStick} label="Память Mac" value={size(memory.used)} note={`из ${size(memory.total)}`}/><Kpi icon={Activity} label="Загрузка CPU" value={pct(s.cpu)} note="Суммарная загрузка процессора"/><Kpi icon={ShieldCheck} label="Давление на память" value={pressure[memory.pressure]||'—'} note="Оценка macOS" tone={memory.pressure==='critical'?'red':memory.pressure==='warning'?'amber':'green'}/></div>}
 {!resources&&<div className="ux-kpi-action"><div><h3>Нужно освободить память?</h3><p>Посмотрите процессы, доступные для завершения.</p></div><button className="ux-button" onClick={()=>navigate('Освободить ресурсы')}>Перейти <ArrowRight size={15}/></button></div>}
 <section className="ux-card"><div className="ux-table-toolbar"><Tabs values={['Все','Приложения','Разработка','Доступны к завершению']} value={filter} set={v=>{setFilter(v);setLimit(60)}}/><span className="ux-muted">{filtered.length} процессов</span></div><div className="ux-filter-toolbar"><SearchBox value={query} onChange={v=>{setQuery(v);setLimit(60)}} placeholder="Имя, PID или проект"/><select aria-label="Сортировка процессов" value={sort} onChange={e=>setSort(e.target.value)}><option value="memory">Сначала больше памяти</option><option value="cpu">Сначала больше CPU</option><option value="write">Сначала больше записи</option></select></div><div className="ux-table-scroll"><table className="ux-table"><thead><tr><th>Процесс</th><th>CPU</th><th>Память</th><th>PID</th><th/></tr></thead><tbody>{filtered.slice(0,limit).map(p=><tr key={p.id}><td><button className="ux-name" onClick={()=>onProcess(p.id)}><span className="ux-app-icon">{(p.group||p.name||'?')[0]}</span><span><b>{p.group||p.name}</b><small>{p.name}{p.project?` · ${p.project}`:''}</small></span></button></td><td className={p.cpu>=90?'ux-red':''}>{pct(p.cpu)}</td><td>{size(p.memory)}</td><td className="ux-muted">{p.pid}</td><td>{protectedProcess(p)?<span className="ux-label" title="Система, Docker, процесс другого пользователя или недоступная идентификация"><Lock size={13}/>Защищён</span>:<button className="ux-button" disabled={disabled} onClick={()=>propose('process.terminate',p.id)}>Завершить</button>}</td></tr>)}</tbody></table></div>{!filtered.length&&<Empty title="Процессы не найдены" text="Измените фильтр или дождитесь обновления агента."/>}{filtered.length>limit&&<div className="ux-card-foot"><button className="ux-button" onClick={()=>setLimit(v=>v+100)}>Показать ещё {Math.min(100,filtered.length-limit)}</button></div>}<div className="ux-card-foot"><Info size={14}/>CPU процесса: 100% = одно ядро. Нажмите имя для истории и подробностей. Завершение относится только к выбранному PID.</div></section>
 {resources&&<div className="ux-inline-note"><Info size={18}/><p>macOS сама управляет кэшем RAM. Монитор не запускает purge и не обещает фиксированное освобождение памяти. После завершения процесса смотрите фактическое давление на память, сжатие и swap выше.</p></div>}</>
}
