import {useEffect,useRef,useState} from 'react';
import {Sparkles,Settings2,HardDrive,Container,GitBranch,Layers,Loader2,X,ShieldCheck,ChevronDown,Cloud,RefreshCw} from 'lucide-react';
import {Data} from './store';
import {formatBytes as size} from './units';

async function post(path:string,body:Data={}){
 const s=await fetch('/api/manage/session').then(r=>r.json());
 const response=await fetch('/api/manage/workspaces/ai/'+path,{method:'POST',headers:{'Content-Type':'application/json','x-sysmo-token':s.token},body:JSON.stringify(body)});
 const value=await response.json();if(!response.ok||value.error)throw Error(value.error||'AI временно недоступен');return value;
}
const when=(ts:number)=>new Date(ts*1000).toLocaleString('ru-RU',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});

export function WorkspaceAI({gateway:g,current,previous,selection,refresh,onProject}:{gateway:Data;current?:Data;previous?:Data;selection:string;refresh:()=>void;onProject:(id:string)=>void}){
 const[open,setOpen]=useState(false),[key,setKey]=useState(''),[model,setModel]=useState(''),[models,setModels]=useState<Data[]>([]),[working,setWorking]=useState(''),[error,setError]=useState('');
 const first=useRef(false),dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(!g)return;if(!first.current){first.current=true;if(!g.configured)setOpen(true)}setModels(g.models||[]);setModel(g.model||'')},[g?.configured,g?.model,JSON.stringify(g?.models)]);
 useEffect(()=>{if(open){dialog.current?.showModal();const prior=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{dialog.current?.close();document.body.style.overflow=prior}}},[open]);
 const close=()=>{setKey('');setError('');setOpen(false)};
 const summary=current?.summary||{},result=g?.result,report=result?.status==='complete'?result.report:null,busy=!!g?.running||working==='analyze';
 const aliases=(s:string)=>s.replace(/проект(?:а|е|у|ом|ы|ов)?[-\s]+(\d+)/gi,'project-$1');
 const text=(s:string)=>aliases(s).replace(/ГБ/g,'GB').replace(/МБ/g,'MB').replace(/КБ/g,'KB').replace(/ТБ/g,'TB').replace(/\bproject-\d+\b/g,alias=>result?.labels?.[alias]?.name?`«${result.labels[alias].name}»`:alias);
 const save=async()=>{setWorking('save');setError('');try{await post('settings',{...key?{api_key:key}:{},...model?{model}:{}});setKey('');const v=await post('models');setModels(v.models);setModel(v.model);refresh();if(v.model){setOpen(false)}else setError('Ключ принят. Выберите модель из списка и сохраните.')}catch(e:any){setError(e.message)}finally{setWorking('')}};
 const analyze=async()=>{if(!g?.configured||!g.model){setOpen(true);return}setWorking('analyze');setError('');try{await post('analyze?'+selection);refresh()}catch(e:any){setError(e.message)}finally{setWorking('')}};
 const mentioned=report?Object.entries(result.labels||{}).filter(([alias])=>aliases(JSON.stringify(report)).includes(alias)):[];
 const facts=[{icon:HardDrive,label:'Свободно на SSD',value:size(summary.disk_free),note:'По данным файловой системы'},
  {icon:Layers,label:'Кандидаты на проверку',value:current?size(summary.build+summary.cache):'—',note:'Build и cache · безопасность не подтверждена'},
  {icon:GitBranch,label:'Локальные изменения',value:current?String(summary.dirty_count):'—',note:'Рабочих копий с изменениями / untracked'},
  {icon:Container,label:'Docker на SSD',value:size(summary.docker_allocated),note:'Docker.raw · выделенные блоки'}];
 return <section className="ux-card ws-ai-dashboard">
  <div className="ws-ai-header"><div className="ws-ai-title"><span className="ws-ai-symbol"><Sparkles size={21}/></span><div><h2>AI-разбор</h2><p>Место, изменения и безопасные следующие шаги.</p></div></div><div className="ws-ai-buttons"><button className="ux-button" onClick={()=>{setError('');setOpen(true)}} disabled={busy} aria-label="Настройки AI"><Settings2 size={15}/><span>Настройки</span></button><button className="ux-button primary" disabled={!current||busy||!!working} onClick={analyze}>{busy?<Loader2 size={15} className="ws-spin"/>:<Sparkles size={15}/>}<span>{busy?'Анализируем…':g?.configured&&g.model?report?'Обновить разбор':'Разобрать снимки':'Подключить Timeweb'}</span></button></div></div>
  <div className="ws-ai-lead">{report?<h3>{text(report.headline)}</h3>:<h3>{current?`Свободно ${size(summary.disk_free)}. Локальные изменения — в ${summary.dirty_count} рабочих копиях.`:'Первый снимок даст основу для разбора.'}</h3>}<p>{current?`Факты на ${when(current.ts)}${previous?` · сравнение с ${when(previous.ts)}`:' · пока без предыдущего снимка'}`:'Сканирование работает в фоне; измерения появятся после завершения.'}</p></div>
  <div className="ws-ai-facts">{facts.map(({icon:Icon,...f})=><div key={f.label}><span><Icon size={16}/>{f.label}</span><strong>{f.value}</strong><small>{f.note}</small></div>)}</div>
  {busy&&<div className="ws-ai-wait" role="status"><Loader2 size={17} className="ws-spin"/><span>Timeweb разбирает обезличенную сводку. Результат сохранится на этом Mac.</span></div>}
  {(error||result?.status==='error')&&<div className="ws-ai-error" role="alert">{error||result?.error}</div>}
  {report?<><div className="ws-ai-columns">{[['observations','Что происходит'],['actions','Что можно сделать'],['risks','Что требует внимания']].map(([k,label])=><div key={k}><h4>{label}</h4><ul>{(report[k]||[]).map((item:string,i:number)=><li key={i}>{text(item)}</li>)}</ul></div>)}</div><details className="ws-ai-reasoning"><summary><ChevronDown size={15}/>Показать обоснование</summary><p>{text(report.reasoning||'')}</p>{mentioned.length>0&&<div className="ws-ai-projects">{mentioned.map(([alias,p]:any)=><button className="ux-button" key={alias} onClick={()=>onProject(p.id)}><GitBranch size={13}/>{p.name}</button>)}</div>}<small>AI: {result.model} · {when(result.created)} · токенов: {result.usage?.total_tokens??'—'}. Карточки выше рассчитаны монитором; объяснение модели может требовать проверки.</small></details></>:<div className="ws-ai-invite"><Cloud size={18}/><p>Получите три коротких вывода по выбранным снимкам: что растёт, где осталась локальная работа и с чего начать проверку.</p></div>}
  <div className="ws-ai-privacy"><ShieldCheck size={14}/><span>В Timeweb отправляются только обезличенные размеры и статусы. Без кода, путей и имён. Анализ — по кнопке, с расходом токенов Gateway. AI не выполняет очистку.</span></div>
  {open&&<dialog ref={dialog} className="ws-dialog ws-ai-settings" aria-label="Настройки Timeweb AI" onCancel={close}><div className="ws-dialog-head"><h2>Подключение Timeweb AI</h2><button className="icon-button" aria-label="Закрыть настройки AI" onClick={close}><X size={19}/></button></div><p>Gateway: <b>api.timeweb.ai/v1</b>. Ключ хранится только в локальной БД этого Mac и не возвращается из API в браузер.</p><label className="ws-root-label">{g?.configured?'Новый ключ (оставьте пустым, чтобы сохранить текущий)':'Ключ AI Gateway'}<input type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} placeholder={g?.configured?'Ключ сохранён на этом Mac':'Вставьте ключ Timeweb'} spellCheck={false}/></label><label className="ws-root-label">Модель<select aria-label="Модель Timeweb" value={model} onChange={e=>setModel(e.target.value)} disabled={!models.length}><option value="">{models.length?'Выберите модель':'Список загрузится после сохранения ключа'}</option>{models.map(m=><option key={m.id} value={m.id}>{m.id}</option>)}</select></label><p className="ws-small">Передаётся компактная сводка выбранных снимков. Запрос запускается только кнопкой «Разобрать снимки»; фоновых платных запросов нет. Настройку и сохранённый результат можно использовать после перезапуска.</p>{error&&<p role="alert" className="ws-ai-error">{error}</p>}<div className="ws-dialog-actions">{g?.configured&&<button className="ux-button" disabled={!!working||busy} onClick={async()=>{setWorking('clear');try{await post('clear');setKey('');setModels([]);setModel('');refresh();close()}catch(e:any){setError(e.message)}finally{setWorking('')}}}>Забыть ключ</button>}<button className="ux-button" onClick={close}>Закрыть</button><button className="ux-button primary" disabled={!!working||busy||(!key&&!g?.configured)} onClick={save}>{working==='save'?<Loader2 size={14} className="ws-spin"/>:<RefreshCw size={14}/>}Проверить и сохранить</button></div></dialog>}
 </section>;
}
