import {useEffect,useMemo,useRef,useState} from 'react';
import {FolderGit2,HardDrive,GitBranch,ShieldCheck,ScanLine,Settings2,Cloud,Square,Loader2,ChevronRight,X,Info,ArrowUpRight,Database,Clock,Search,Lock,Container} from 'lucide-react';
import {Chart} from './Chart';
import {WorkspaceAI} from './WorkspaceAI';
import {formatBytes as size,GB} from './units';
import {Data} from './store';
import './management.css';
import './workspaces.css';

const when=(ts?:number)=>ts?new Date(ts*1000).toLocaleString('ru-RU',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}):'—';
const delta=(a:unknown,b:unknown)=>typeof a==='number'&&typeof b==='number'?a-b:null;
const change=(n:number|null)=>n===null?'—':`${n>0?'+':n<0?'−':''}${size(Math.abs(n))}`;
const published:Record<string,string>={confirmed:'Коммит подтверждён',not_checked:'Remote не проверен',no_upstream:'Нет upstream',unavailable:'Remote недоступен',missing_ref:'Ветка не найдена на remote',unknown_tip:'Не хватает локальных объектов',not_reachable:'Коммит не входит в upstream'};
async function api(path:string,body?:Data){
 const headers:Record<string,string>={};
 if(body){const session=await fetch('/api/manage/session').then(r=>r.json());headers['Content-Type']='application/json';headers['x-sysmo-token']=session.token;}
 const response=await fetch(path,{method:body?'POST':'GET',headers,body:body?JSON.stringify(body):undefined});
 const value=await response.json();if(!response.ok)throw Error(value.error||'Агент недоступен');return value;
}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const d=ref.current;d?.showModal();const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{d?.close();document.body.style.overflow=previous}},[]);
 return <dialog ref={ref} className="ws-dialog" aria-label={title} onCancel={close}><div className="ws-dialog-head"><h2>{title}</h2><button className="icon-button" aria-label="Закрыть" onClick={close}><X size={19}/></button></div>{children}</dialog>;
}
function Notice({title,children}:{title:string;children:React.ReactNode}){return <div className="ws-empty"><Database size={26}/><h3>{title}</h3><p>{children}</p></div>}

export function Workspaces(){
 const[data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[action,setAction]=useState(''),[message,setMessage]=useState('');
 const[before,setBefore]=useState(''),[after,setAfter]=useState(''),[revision,setRevision]=useState(0),[query,setQuery]=useState(''),[filter,setFilter]=useState('Все');
 const[metric,setMetric]=useState('total'),[days,setDays]=useState(30),[selected,setSelected]=useState<Data|null>(null),[settings,setSettings]=useState(false),[roots,setRoots]=useState('');
 const requestQuery=new URLSearchParams({...before?{before}:{},...after?{after}:{}}).toString();
 useEffect(()=>{
  const abort=new AbortController();let working=false;
  const read=async()=>{if(working)return;working=true;try{const r=await fetch('/api/workspaces?'+requestQuery,{signal:abort.signal});const v=await r.json();if(!r.ok)throw Error(v.error||'История недоступна');if(!abort.signal.aborted){setData(v);setError('')}}catch(e:any){if(e.name!=='AbortError')setError(e.message)}finally{working=false}};
  read();const timer=setInterval(read,10000);return()=>{abort.abort();clearInterval(timer)};
 },[requestQuery,revision]);
 const run=async(path:string,body:Data,success:string)=>{setAction(path);setMessage('');try{await api('/api/manage/workspaces/'+path,body);setMessage(success);setRevision(v=>v+1);return true}catch(e:any){setMessage(e.message);return false}finally{setAction('')}};
 const current=data?.current,previous=data?.previous,status=data?.status||{},busy=!!data?.running,summary=current?.summary||{},prior=previous?.summary||{};
 const history:Data[]=data?.snapshots||[],projects:Data[]=current?.projects||[],repos:Data[]=current?.repositories||[];
 const priorProjects=new Map<string,Data>((previous?.projects||[]).map((p:Data)=>[p.id,p]));
 const sameScope=!!current&&!!previous&&current.scope===previous.scope;
 const difference=(p:Data)=>{const old=priorProjects.get(p.id);return sameScope&&p.complete&&old?.complete?delta(p.size,old.size):null};
 const rows=projects.filter(p=>(p.name+' '+p.path+' '+p.branch).toLowerCase().includes(query.toLowerCase())&&(filter==='Все'||filter==='Есть изменения'&&(p.changed+p.untracked+p.conflicts>0)||filter==='Растут'&&(difference(p)||0)>0)).sort((a,b)=>filter==='Растут'?(difference(b)||0)-(difference(a)||0):b.size-a.size);
 const dirty=projects.filter(p=>p.changed+p.untracked+p.conflicts>0),stashes=repos.reduce((n,r)=>n+(r.stashes||0),0);
 const branches:Data[]=repos.flatMap(r=>r.branches||[]),confirmed=branches.filter(b=>b.published==='confirmed').length;
 const growth=projects.map((p):Data=>({...p,growth:difference(p)})).filter(p=>p.growth!==null&&p.growth>50_000_000).sort((a,b)=>b.growth-a.growth);
 const sources=useMemo(()=>history.filter(h=>h.scope===current?.scope).map(h=>({ts:h.ts,metrics:{...h.summary,...h.status!=='complete'?{total:null,dependencies:null,build:null,git_bytes:null,cache:null}: {}}})),[data?.snapshots,current?.scope]);
 const series=useMemo(()=>[{key:metric,label:({total:'Проекты и Git',dependencies:'Зависимости',build:'Сборки',git_bytes:'Данные Git',cache:'Кэши',docker_allocated:'Docker.raw',disk_free:'Свободно на SSD'} as Data)[metric]+', GB',color:metric==='docker_allocated'?'#a18cd1':'#6bafdf',scale:GB}],[metric]);
 const visiblePoints=sources.filter(p=>p.ts>=Date.now()/1000-days*86400&&typeof p.metrics[metric]==='number').length;
 return <div className="studio embedded ws-page">
  <div className="ws-heading"><div><div className="eyebrow">РАЗРАБОТКА · ИСТОРИЯ РОСТА</div><h1>Рабочие проекты</h1><p>Что занимает место, что растёт и какая работа ещё остаётся только на Mac.</p></div><button className="ux-button" onClick={()=>{setRoots((data?.config.roots||[]).join('\n'));setSettings(true)}} disabled={!data||busy}><Settings2 size={15}/>Папки</button></div>
  <div className="ws-tools"><span className="ux-label"><ShieldCheck size={15}/>Только наблюдение</span><span className="ux-label"><Clock size={14}/>Снимок каждые 6 часов</span><div className="ws-actions"><button className="ux-button" disabled={busy||!!action||!data} onClick={()=>run('scan',{verify_remote:true},'Запущен снимок со сверкой remote. Git не изменяется.')}><Cloud size={15}/>Сверить с remote</button><button className="ux-button primary" disabled={busy||!!action||!data} onClick={()=>run('scan',{},'Сканирование запущено в фоне.')}><ScanLine size={15}/>Снять сейчас</button></div></div>
  {(busy||status.status==='scanning')&&<div className="ws-progress" role="status"><Loader2 size={19} className="ws-spin"/><div><strong>{status.phase||'Запускаем сборщик'}</strong><span>{Number(status.visited||0).toLocaleString('ru-RU')} объектов · найдено проектов: {status.found||0}</span><small title={status.current}>{status.current||'Снимок появится после окончания обхода'}</small></div><button className="ux-button" disabled={!!action} onClick={()=>run('cancel',{},'Остановка запрошена. Предыдущие снимки сохранятся.')}><Square size={13}/>Остановить</button></div>}
  {error&&<div role="alert" className="ux-live-alert">{error}</div>}
  {(message||status.status==='error'||status.status==='cancelled')&&<div className="ws-message" role="status"><Info size={16}/><span>{message||(status.status==='cancelled'?'Обход остановлен. Последний завершённый снимок остаётся в истории.':status.message)}</span>{message&&<button className="icon-button" aria-label="Скрыть сообщение" onClick={()=>setMessage('')}><X size={15}/></button>}</div>}
  {data&&<WorkspaceAI gateway={data.gateway} current={current} previous={previous} selection={requestQuery} refresh={()=>setRevision(v=>v+1)} onProject={id=>{const p=projects.find(p=>p.id===id);if(p)setSelected(p)}}/>}
  <section className="ws-technical"><div className="ws-technical-heading"><FolderGit2 size={17}/><span>Технические детали<small>История роста, сравнение снимков, Git и Docker</small></span></div>
  <section className="ux-card ws-history"><div className="ws-section-head"><div><h2>Как меняется занятое место</h2><p>История выбранной области поиска. Неполные измерения оставляют разрыв.</p></div><div className="ws-controls"><select aria-label="Показатель истории проектов" value={metric} onChange={e=>setMetric(e.target.value)}>{Object.entries({total:'Проекты и Git',dependencies:'Зависимости',build:'Сборки',git_bytes:'Данные Git',cache:'Кэши',docker_allocated:'Docker.raw',disk_free:'Свободно на SSD'}).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select aria-label="Период истории проектов" value={days} onChange={e=>setDays(+e.target.value)}><option value={7}>7 дней</option><option value={30}>30 дней</option><option value={90}>90 дней</option></select></div></div>{visiblePoints>=2?<Chart source={sources} period={days*86400} lines={series} height={250}/>:<Notice title={current?'Нужны два полных измерения':'Собираем первый снимок'}>{current?'Следующий снимок создастся автоматически. Можно запустить его вручную. История начинается с момента включения мониторинга.':'Обход работает в фоне. Здесь появятся реальные размеры проектов, Git и Docker.'}</Notice>}</section>
  {current&&<>
  <section className="ux-card ws-comparison"><div className="ws-section-head"><div><h2>Сравнение снимков</h2><p>Изменения за выбранный интервал, а не оценка освобождаемого места.</p></div><span className="ws-pill">{current.status==='complete'?'Полный снимок':'Частичный снимок'}</span></div><div className="ws-snapshot-select"><label>Было<select aria-label="Снимок было" value={before} onChange={e=>setBefore(e.target.value)}><option value="">Предыдущий в этой области</option>{history.map(h=><option key={h.id} value={h.id}>{when(h.ts)} · №{h.id}{h.status==='partial'?' · частично':''}</option>)}</select></label><ChevronRight size={18}/><label>Стало<select aria-label="Снимок стало" value={after} onChange={e=>setAfter(e.target.value)}><option value="">Последний снимок</option>{history.map(h=><option key={h.id} value={h.id}>{when(h.ts)} · №{h.id}{h.status==='partial'?' · частично':''}</option>)}</select></label></div>
  <div className="ws-comparison-values">{[['total','Проекты и Git'],['dependencies','Зависимости'],['build','Сборки'],['git_bytes','Данные Git']].map(([key,label])=>{const d=data?.comparable?delta(summary[key],prior[key]):null;return <div key={key}><span>{label}</span><strong className={d!==null&&d>0?'ws-growth':''}>{change(d)}</strong><small>{previous?`${size(prior[key])} → ${size(summary[key])}`:'Пока есть один снимок'}</small></div>})}</div>
  <div className="ux-card-foot"><Info size={14}/>{!previous?'Предыдущего снимка ещё нет.':!sameScope?'Области поиска различаются: общий прирост не рассчитывается.':!data?.comparable?'Есть неполные измерения: общий прирост скрыт. Полностью измеренные рабочие копии можно сравнить ниже.':`${when(previous.ts)} → ${when(current.ts)}. Новые и исчезнувшие проекты отмечаются отдельно.`}</div></section>
  <div className="ws-rule-section"><section className="ux-card ws-attention"><div className="ws-section-head"><div><h2>На что обратить внимание</h2><p>Причины для проверки, без разрешения на удаление.</p></div><ShieldCheck size={20}/></div>
   {summary.disk_free<15*GB&&<div className="ws-finding warning"><HardDrive size={18}/><div><b>Свободно на диске: {size(summary.disk_free)}</b><p>Остаток меньше 15 GB на момент снимка. Начните с самых крупных источников роста.</p></div></div>}
   <div className="ws-finding"><GitBranch size={18}/><div><b>{dirty.length?`${dirty.length} рабочих копий с локальными изменениями`:'В измеренных копиях нет видимых изменений'}</b><p>{stashes?`Записей stash: ${stashes}. `:''}Untracked и ignored файлы не защищены публикацией коммита. Ошибок чтения Git: {summary.git_unknown||0}.</p></div></div>
   <div className="ws-finding"><Cloud size={18}/><div><b>{confirmed} из {branches.length} веток подтверждены на remote</b><p>Подтверждение относится к коммиту и времени сверки. Остальные ветки требуют проверки, а не автоматической очистки.</p></div></div>
   {growth.length?growth.slice(0,3).map(p=><div className="ws-finding" key={p.id}><ArrowUpRight size={18}/><div><button className="ws-text-button" onClick={()=>setSelected(p)}>{p.name}</button><p>Рабочая копия выросла на {change(p.growth)} между снимками.</p></div></div>):<div className="ws-finding"><Clock size={18}/><div><b>{previous?'Нет подтверждённого роста копий более 50 MB':'Тренд станет виден со следующим снимком'}</b><p>Добавленные папки и неполные измерения не выдаются за рост.</p></div></div>}
  </section></div>
  <section className="ux-card"><div className="ws-section-head"><div><h2>Рабочие копии</h2><p>Общие данные Git вынесены отдельно. Ветка сама по себе не считается копией папки.</p></div><span className="ux-muted">{rows.length} из {projects.length}</span></div><div className="ws-project-filters"><label className="ws-search"><Search size={16}/><input aria-label="Поиск рабочих копий" placeholder="Проект, папка или ветка" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Фильтр рабочих копий" value={filter} onChange={e=>setFilter(e.target.value)}><option>Все</option><option>Есть изменения</option><option>Растут</option></select></div><div className="ux-table-scroll"><table className="ux-table ws-project-table"><thead><tr><th>Проект / ветка</th><th>На диске</th><th>Изменение</th><th>Локальная работа</th><th/></tr></thead><tbody>{rows.map(p=>{const d=difference(p);return <tr key={p.id}><td><button className="ux-name" onClick={()=>setSelected(p)}><FolderGit2 size={18}/><span><b>{p.name}</b><small title={p.path}>{p.branch||'Без ветки'} · {p.path}</small></span></button></td><td>{size(p.size)}{!p.complete&&<small className="ws-cell-note">Частично</small>}</td><td className={d!==null&&d>0?'ws-growth':''}>{sameScope&&!priorProjects.has(p.id)?'Новая в области':change(d)}</td><td>{!p.git_ok?<span className="ws-pill">Git недоступен</span>:p.changed+p.untracked+p.conflicts?<><span className="ws-pill amber">{p.changed} изм. · {p.untracked} untracked</span>{p.conflicts>0&&<small className="ws-cell-note">Конфликтов: {p.conflicts}</small>}</>:<span className="ws-pill">Нет видимых изменений</span>}</td><td><button className="icon-button" aria-label={'Подробнее: '+p.name} onClick={()=>setSelected(p)}><ChevronRight size={17}/></button></td></tr>})}</tbody></table></div>{!rows.length&&<Notice title="Рабочих копий не найдено">Проверьте выбранные папки или измените фильтр. Учитываются папки с .git, включая worktrees.</Notice>}<div className="ux-card-foot"><Info size={14}/>Ignored файлы входят в размер, но не в статус Git. Количество untracked может обозначать целые папки.</div></section>
  {sameScope&&(previous?.projects||[]).some((p:Data)=>!projects.some(x=>x.id===p.id))&&<div className="ws-message"><Info size={16}/><span>{previous.projects.filter((p:Data)=>!projects.some(x=>x.id===p.id)).length} рабочих копий больше не обнаружено в области. Это может быть перенос или недоступность папки; освобождение места не подтверждено.</span></div>}
  <DockerHistory current={current.docker} previous={previous?.docker}/>
  <div className="ws-footnote"><Info size={15}/><p>Измерение: {when(current.started)} — {when(current.ts)}. Выделенные блоки файлов, без перехода по symlink. APFS clones и снимки файловой системы могут разделять блоки, поэтому сумма не равна месту, которое освободится при удалении. История хранится 90 дней, до 1000 снимков.</p></div>
  </>}
  </section>
  {settings&&<Modal title="Папки для мониторинга" close={()=>setSettings(false)}><p>Ищем Git-проекты внутри этих папок. По одной папке на строку. Только внутри домашней папки; ссылки на другие папки не обходим.</p><label className="ws-root-label">Корни поиска<textarea autoFocus rows={6} value={roots} onChange={e=>setRoots(e.target.value)} spellCheck={false}/></label><p className="ws-small">Смена области сохраняет старую историю. Для новой области соберите новый снимок. Обычный сбор не обращается к remote.</p><div className="ws-dialog-actions"><button className="ux-button" onClick={()=>setSettings(false)}>Отмена</button><button className="ux-button primary" disabled={!!action||busy} onClick={async()=>{if(await run('settings',{roots:roots.split('\n').map(v=>v.trim()).filter(Boolean)},'Папки сохранены. Запустите новый снимок.')){setBefore('');setAfter('');setSettings(false)}}}>Сохранить папки</button></div>{message&&<p role="status">{message}</p>}</Modal>}
  {selected&&<ProjectDetail project={selected} repo={repos.find(r=>r.id===selected.repo_id)} close={()=>setSelected(null)}/>}
 </div>;
}

function ProjectDetail({project:p,repo:r,close}:{project:Data;repo?:Data;close:()=>void}){
 const branches:Data[]=r?.branches||[];
 return <Modal title={p.name} close={close}><p className="ws-path">{p.path}</p><div className="ws-detail-sizes">{[['source','Рабочие файлы'],['dependencies','Зависимости'],['build','Сборки'],['cache','Кэши']].map(([key,label])=><div key={key}><span>{label}</span><strong>{size(p.sizes[key])}</strong></div>)}</div><p className="ws-small">Категории определяются по именам папок. Даже в build или dist могут быть ценные файлы. Это не список для удаления.</p><div className="ws-repo-summary"><span>Общие данные Git <b>{size(r?.git_bytes)}</b></span><span>Stash <b>{r?.stashes??'—'}</b></span><span>Git проверен <b>{when(p.git_at)}</b></span></div>{r?.outside_scope&&<p>Каталог Git находится за пределами выбранных папок. Размер не измерялся.</p>}
  {p.branch==='(detached)'&&<p className="ws-detached">Detached HEAD: текущий коммит не привязан к активной ветке. Его публикация отдельно не проверялась.</p>}<h3>Локальные ветки репозитория</h3><p className="ws-small">Ahead / behind — по локальному upstream, он может быть устаревшим. Подтверждение remote не защищает незакоммиченные изменения, ignored файлы и stash.</p><div className="ux-table-scroll"><table className="ux-table ws-branches"><thead><tr><th>Ветка</th><th>Локальный upstream</th><th>Публикация коммита</th></tr></thead><tbody>{branches.map(b=><tr key={b.name}><td><b>{b.name}</b><small className="ws-cell-note">Коммит: {when(b.committed)}</small></td><td>{b.upstream||'Нет'}<small className="ws-cell-note">{b.track==='[gone]'?'Upstream отсутствует в локальных refs':b.track||(b.upstream?'Локальные refs совпадают':'Сравнение не задано')}</small></td><td><span className={'ws-pill '+(b.published==='confirmed'?'green':'')}>{published[b.published]||'Неизвестно'}</span><small className="ws-cell-note">{b.verified_at?when(b.verified_at):'Запустите сверку с remote'}</small></td></tr>)}</tbody></table></div>{!branches.length&&<p>Локальных веток нет или Git не предоставил данные.</p>}
  <h3>Зарегистрированные worktrees</h3><div className="ws-worktree-list">{r?.worktrees?.map((w:Data)=><div key={w.worktree}><FolderGit2 size={17}/><span>{w.worktree}<small>{w.branch||'Detached HEAD'}{w.prunable?' · Git помечает prunable, требуется проверка':''}</small></span>{w.locked&&<span className="ws-pill"><Lock size={12}/>Locked</span>}</div>)}</div><div className="ws-dialog-actions"><button className="ux-button" onClick={close}>Закрыть</button></div></Modal>;
}

function DockerHistory({current:c,previous:p}:{current:Data;previous?:Data}){
 const available=c?.status==='available',prior=p?.status==='available'&&!!c?.engine&&c.engine===p?.engine;
 const total=(objects:Data[]|undefined)=>objects&&objects.every(o=>typeof o.size==='number')?objects.reduce((n,o)=>n+o.size,0):null;
 const groups=[['containers','Контейнеры · записываемые слои'],['images','Образы · с общими слоями'],['volumes','Тома · данные приложений'],['cache','Кэш сборки']];
 const stopped=(c?.containers||[]).filter((o:Data)=>['exited','created'].includes(o.state));
 const old=stopped.filter((o:Data)=>o.finished&&!o.finished.startsWith('0001')&&Date.now()-Date.parse(o.finished)>30*86400000);
 return <section className="ux-card"><div className="ws-section-head"><div><h2>Docker: накопление данных</h2><p>{available?`${stopped.length} остановленных контейнеров · ${old.length} остановлены более 30 дней`:'Docker был недоступен на момент снимка. Это не нулевое использование.'}</p></div><Container size={20}/></div><div className="ws-docker-physical"><span>Docker.raw на SSD <b>{size(c?.allocated)}</b></span><span>Изменение <b className="ws-growth">{change(available&&prior?delta(c.allocated,p?.allocated):null)}</b></span><span>Слои образов по Docker <b>{size(c?.layers)}</b></span></div><div className="ux-table-scroll"><table className="ux-table"><thead><tr><th>Категория</th><th>Объектов</th><th>Появилось / исчезло</th><th>Размер по Docker</th><th>Изменение</th></tr></thead><tbody>{groups.map(([key,label])=>{const objects:Data[]|undefined=c?.[key],old:Data[]|undefined=prior?p?.[key]:undefined;const newIds=new Set(objects?.map(o=>o.id)),oldIds=new Set(old?.map(o=>o.id));return <tr key={key}><td>{label}</td><td>{objects?.length??'—'}</td><td>{objects&&old?`+${objects.filter(o=>!oldIds.has(o.id)).length} / −${old.filter(o=>!newIds.has(o.id)).length}`:'—'}</td><td>{size(total(objects))}</td><td>{change(delta(total(objects),total(old)))}</td></tr>})}</tbody></table></div><div className="ux-card-foot"><ShieldCheck size={15}/>Тома, Docker.raw и папки Mac не удаляются. Возраст не означает ненужность. Разницу считаем только для одного подтверждённого движка. Общие слои нельзя складывать как освобождаемое место.</div></section>;
}
