use serde_json::{json,Value};use std::collections::{HashMap,VecDeque};
pub struct Diagnostics{window:VecDeque<Value>,active:HashMap<String,f64>,emitted:HashMap<String,f64>,pressure:String}
impl Diagnostics{
 pub fn new()->Self{Self{window:VecDeque::new(),active:HashMap::new(),emitted:HashMap::new(),pressure:String::new()}}
 pub fn sample(&mut self,s:&Value,p:&[Value])->(Value,Vec<(String,Value)>){let ts=s["ts"].as_f64().unwrap();if self.window.back().is_some_and(|v|ts-v["ts"].as_f64().unwrap_or(ts)>5.0){self.window.clear();self.active.clear();}self.window.push_back(s.clone());while self.window.front().is_some_and(|v|ts-v["ts"].as_f64().unwrap()>600.0){self.window.pop_front();}let mut events=vec![];let pressure=s["memory"]["pressure"].as_str().unwrap_or("unavailable");if pressure!=self.pressure{events.push(("memory_pressure".into(),json!({"from":self.pressure,"to":pressure})));self.pressure=pressure.into();}
 let rules=[("memory_pressure",pressure=="warning"||pressure=="critical",if pressure=="critical"{10.0}else{60.0},"Повышенное давление на память","memory"),("cpu",s["cpu"].as_f64().is_some_and(|v|v>85.0),60.0,"Длительная высокая загрузка CPU","cpu"),("temperature",s["hardware"]["temp"]["cpu_temp_avg"].as_f64().is_some_and(|v|v>90.0),60.0,"Высокая температура CPU","cpu"),("disk",s["disk"]["write"].as_f64().is_some_and(|v|v>30.0*1024.0*1024.0),30.0,"Продолжительная запись на накопитель","write"),("network",s["network"]["download"].as_f64().is_some_and(|v|v>50.0*1024.0*1024.0),30.0,"Высокая сетевая активность","network")];
 let mut findings=vec![];for(code,condition,duration,title,key)in rules{if !condition{self.active.remove(code);continue}let start=*self.active.entry(code.into()).or_insert(ts);if ts-start<duration{continue}let mut top:Vec<_>=p.iter().collect();top.sort_by(|a,b|b[key].as_f64().unwrap_or(0.0).total_cmp(&a[key].as_f64().unwrap_or(0.0)));let finding=json!({"code":code,"title":title,"duration":ts-start,"since":start,"pressure":pressure,"swap":s["memory"]["swap"],"consumers":top.into_iter().take(3).map(|p|json!({"id":p["id"],"name":p["label"],"project":p["project"],"value":p[key]})).collect::<Vec<_>>(),"metric":key});if self.emitted.get(code).is_none_or(|t|ts-t>600.0){events.push((code.into(),finding.clone()));self.emitted.insert(code.into(),ts);}findings.push(finding);}
 let observed=self.window.front().map(|v|ts-v["ts"].as_f64().unwrap()).unwrap_or(0.0);let warning=self.window.iter().filter(|v|v["memory"]["pressure"]=="warning"||v["memory"]["pressure"]=="critical").count();
 (json!({"findings":findings,"observed_seconds":observed,"pressure_elevated_percent":if self.window.is_empty(){None}else{Some(warning as f64/self.window.len() as f64*100.0)},"note":"Совпадение нагрузки во времени показывает вероятный источник, но не доказывает причинность."}),events)
 }
}
#[cfg(test)]mod tests{use super::*;#[test]fn one_spike_does_not_trigger(){let mut d=Diagnostics::new();let(f,_)=d.sample(&json!({"ts":100.0,"cpu":99.0,"memory":{"pressure":"normal"}}),&[]);assert!(f["findings"].as_array().unwrap().is_empty());let(f,_)=d.sample(&json!({"ts":101.0,"cpu":0.0,"memory":{"pressure":"normal"}}),&[]);assert!(f["findings"].as_array().unwrap().is_empty());}}
