mod workspaces;mod management;mod storage_scan;mod collector;mod docker;mod history;mod diagnostics;
use axum::{Router,extract::{State,Query,Path,WebSocketUpgrade,ws::{WebSocket,Message}},http::{StatusCode,Request},middleware::{self,Next},response::{Response,IntoResponse},routing::{get,post},Json};
use serde_json::{json,Value};use std::{collections::{HashMap,HashSet},sync::{Arc,Mutex,RwLock},path::PathBuf,time::{Duration,Instant}};
use tokio::sync::broadcast;use tower_http::services::ServeDir;
#[derive(Clone)]struct App {workspaces:Arc<workspaces::Workspaces>,management:Arc<management::Management>,current:Arc<RwLock<Value>>,processes:Arc<RwLock<Vec<Value>>>,docker:Arc<RwLock<Value>>,db:Arc<Mutex<history::History>>,history_path:Arc<PathBuf>,watch:Arc<Mutex<HashMap<String,Instant>>>,tx:broadcast::Sender<Arc<String>>}
#[tokio::main(flavor="multi_thread",worker_threads=2)]
async fn main()->Result<(),Box<dyn std::error::Error>>{
 unsafe{libc::umask(0o077);}
 let root=std::env::var("SYSTEM_MONITOR_ROOT").map(PathBuf::from).unwrap_or_else(|_|PathBuf::from(env!("CARGO_MANIFEST_DIR")).parent().unwrap().to_path_buf());
 let data=std::env::var("SYSTEM_MONITOR_DATA").map(PathBuf::from).unwrap_or_else(|_|PathBuf::from(std::env::var("HOME").unwrap()).join("Library/Application Support/System Monitor"));std::fs::create_dir_all(&data)?;
 let history_path=Arc::new(data.join("history.sqlite"));
 let (tx,_)=broadcast::channel(8);let app=App{workspaces:Arc::new(workspaces::Workspaces::new(root.clone(),data.clone())),management:Arc::new(management::Management::new(data.join("storage-scan.json"))),current:Arc::new(RwLock::new(json!({"status":"starting"}))),processes:Arc::new(RwLock::new(vec![])),docker:Arc::new(RwLock::new(json!({"status":"checking","containers":[]}))),db:Arc::new(Mutex::new(history::History::open(&history_path)?)),history_path,watch:Arc::new(Mutex::new(HashMap::new())),tx};
 tokio::spawn(workspaces::schedule(app.workspaces.clone()));
 let scan_app=app.management.clone();tokio::spawn(async move{loop{management::start_scan(scan_app.clone());tokio::time::sleep(Duration::from_secs(6*3600)).await;}});
 let disk_layout=Arc::new(RwLock::new(json!({"status":"loading"})));let dl=disk_layout.clone();let dl_root=root.clone();
 std::thread::Builder::new().name("disk-layout".into()).spawn(move||loop{let value=std::process::Command::new("/usr/bin/python3").arg(dl_root.join("scripts/disk_layout.py")).stderr(std::process::Stdio::null()).output().ok().filter(|o|o.status.success()).and_then(|o|serde_json::from_slice::<Value>(&o.stdout).ok()).unwrap_or_else(||json!({"status":"unavailable"}));*dl.write().unwrap()=value;std::thread::sleep(Duration::from_secs(60));})?;
 let hardware=Arc::new(RwLock::new((Instant::now(),Value::Null,String::from("starting"))));let hw=hardware.clone();
 std::thread::Builder::new().name("hardware".into()).spawn(move||loop{match macmon::Sampler::new(){Ok(mut sampler)=>{let ane_available=macmon::sources::IOReport::new(vec![("Energy Model",None)]).map(|r|r.get_sample(10).any(|x|x.channel.starts_with("ANE")&&matches!(x.unit.as_str(),"mJ"|"uJ"|"nJ"))).unwrap_or(false);loop{match sampler.get_metrics(1000){Ok(m)=>{let mut value=serde_json::to_value(m).unwrap_or(Value::Null);value["ane_power_available"]=json!(ane_available);if !ane_available{value["ane_power"]=Value::Null;}for key in ["cpu_temp_avg","gpu_temp_avg"]{if value["temp"][key].as_f64().is_none_or(|v|v<=0.0){value["temp"][key]=Value::Null;}}*hw.write().unwrap()=(Instant::now(),value,"available".into());},Err(e)=>{*hw.write().unwrap()=(Instant::now(),Value::Null,e.to_string());break}}}},Err(e)=>{*hw.write().unwrap()=(Instant::now(),Value::Null,e.to_string());}}std::thread::sleep(Duration::from_secs(10));})?;
 let dapp=app.clone();tokio::spawn(async move{let mut d=docker::Docker::new();loop{*dapp.docker.write().unwrap()=d.sample().await;tokio::time::sleep(Duration::from_secs(2)).await;}});
 let collect=app.clone();std::thread::Builder::new().name("collector".into()).spawn(move||{let mut c=collector::Collector::new();let mut dg=diagnostics::Diagnostics::new();let mut prior:HashMap<String,Value>=HashMap::new();loop{let start=Instant::now();let (mut system,processes)=c.sample();system["disk_layout"]=disk_layout.read().unwrap().clone();{let h=hardware.read().unwrap();system["hardware"]=if h.0.elapsed()<Duration::from_secs(5){h.1.clone()}else{Value::Null};system["sensor_status"]=json!(if h.0.elapsed()<Duration::from_secs(5){h.2.as_str()}else{"stale"});}
 let docker=collect.docker.read().unwrap().clone();let(diag,events)=dg.sample(&system,&processes);system["diagnostics"]=diag;
 let watched={let mut w=collect.watch.lock().unwrap();w.retain(|_,t|t.elapsed()<Duration::from_secs(120));w.keys().cloned().collect::<HashSet<_>>()};
 {let mut db=collect.db.lock().unwrap();if let Err(e)=db.record(&system,&processes,&docker,&watched){system["history_error"]=json!(e.to_string());}for(code,value)in events{if let Err(e)=db.event(&code,&value){eprintln!("event history: {e}");}}}
 let current:HashMap<String,Value>=processes.iter().filter_map(|p|p["id"].as_str().map(|id|(id.into(),p.clone()))).collect();let changed:Vec<Value>=current.iter().filter_map(|(id,p)|{match prior.get(id){None=>Some(p.clone()),Some(old)=>{let mut patch=serde_json::Map::new();for(k,v)in p.as_object().unwrap(){if old.get(k)!=Some(v){patch.insert(k.clone(),v.clone());}}if patch.is_empty(){None}else{patch.insert("id".into(),json!(id));Some(Value::Object(patch))}}}}).collect();let removed:Vec<_>=prior.keys().filter(|id|!current.contains_key(*id)).collect();
 system["collector_ms"]=json!(start.elapsed().as_secs_f64()*1000.0);*collect.current.write().unwrap()=system.clone();*collect.processes.write().unwrap()=processes;
 let payload=json!({"type":"sample","system":system,"changed":changed,"removed":removed,"docker":docker});let _=collect.tx.send(Arc::new(payload.to_string()));prior=current;
 std::thread::sleep(Duration::from_secs(1).saturating_sub(start.elapsed()));}})?;
 let router=Router::new().route("/api/manage/workspaces/ai/settings",post(workspaces::ai_settings)).route("/api/manage/workspaces/ai/models",post(workspaces::ai_models)).route("/api/manage/workspaces/ai/clear",post(workspaces::ai_clear)).route("/api/manage/workspaces/ai/analyze",post(workspaces::ai_analyze)).route("/api/workspaces",get(workspaces::view)).route("/api/workspaces/export",get(workspaces::export)).route("/api/manage/workspaces/scan",post(workspaces::scan)).route("/api/manage/workspaces/cancel",post(workspaces::cancel)).route("/api/manage/workspaces/settings",post(workspaces::settings)).route("/api/manage/session",get(management::session)).route("/api/manage/docker",get(management::inventory)).route("/api/manage/plan",post(management::plan)).route("/api/manage/execute",post(management::execute)).route("/api/manage/storage",get(management::scan)).route("/api/manage/storage/start",post(management::scan_start)).route("/api/manage/storage/cancel",post(management::scan_cancel)).route("/api/system",get(system)).route("/api/processes",get(processes)).route("/api/process/{id}",get(process)).route("/api/history",get(history_query)).route("/api/events",get(events)).route("/api/docker",get(docker_current)).route("/api/storage",get(storage)).route("/api/live",get(live)).fallback_service(ServeDir::new(root.join("frontend/dist"))).layer(middleware::from_fn_with_state(app.clone(),security)).with_state(app);
 let listener=tokio::net::TcpListener::bind("127.0.0.1:9899").await?;println!("System Monitor: http://127.0.0.1:9899");axum::serve(listener,router).await?;Ok(())
}
fn snapshot(a:&App)->Value{json!({"type":"snapshot","system":a.current.read().unwrap().clone(),"processes":a.processes.read().unwrap().clone(),"docker":a.docker.read().unwrap().clone()})}
async fn system(State(a):State<App>)->Json<Value>{Json(a.current.read().unwrap().clone())}
async fn processes(State(a):State<App>)->Json<Value>{Json(json!(a.processes.read().unwrap().clone()))}
async fn docker_current(State(a):State<App>)->Json<Value>{Json(a.docker.read().unwrap().clone())}
async fn storage(State(a):State<App>)->Json<Value>{Json(a.current.read().unwrap()["disks"].clone())}
#[derive(serde::Deserialize)]struct Range{since:Option<f64>,until:Option<f64>}
async fn history_query(State(a):State<App>,Query(q):Query<Range>)->Result<Json<Value>,StatusCode>{let now=collector::now();let until=q.until.unwrap_or(now).min(now);let since=q.since.unwrap_or(until-900.0).max(now-2592000.0);if !since.is_finite()||!until.is_finite()||since>until{return Err(StatusCode::BAD_REQUEST)}let path=a.history_path.clone();tokio::task::spawn_blocking(move||history::History::reader(&path).and_then(|db|db.query(since,until)).map(Json).map_err(|_|StatusCode::INTERNAL_SERVER_ERROR)).await.map_err(|_|StatusCode::INTERNAL_SERVER_ERROR)?}
async fn process(State(a):State<App>,Path(id):Path<String>,Query(q):Query<Range>)->Result<Json<Value>,StatusCode>{if id.len()>180{return Err(StatusCode::BAD_REQUEST)}a.watch.lock().unwrap().insert(id.clone(),Instant::now());let current=a.processes.read().unwrap().iter().find(|p|p["id"]==id).cloned();let since=q.since.unwrap_or(collector::now()-900.0).max(collector::now()-86400.0);let path=a.history_path.clone();let h=tokio::task::spawn_blocking(move||history::History::reader(&path).and_then(|db|db.process(&id,since))).await.map_err(|_|StatusCode::INTERNAL_SERVER_ERROR)?.map_err(|_|StatusCode::INTERNAL_SERVER_ERROR)?;Ok(Json(json!({"process":current,"history":h})))}
async fn events(State(a):State<App>)->Result<Json<Value>,StatusCode>{let path=a.history_path.clone();tokio::task::spawn_blocking(move||history::History::reader(&path).and_then(|db|db.events()).map(Json).map_err(|_|StatusCode::INTERNAL_SERVER_ERROR)).await.map_err(|_|StatusCode::INTERNAL_SERVER_ERROR)?}
async fn live(ws:WebSocketUpgrade,State(a):State<App>)->impl IntoResponse{ws.on_upgrade(move|socket|stream(socket,a))}
async fn stream(mut socket:WebSocket,a:App){let mut rx=a.tx.subscribe();if socket.send(Message::Text(snapshot(&a).to_string().into())).await.is_err(){return}loop{tokio::select!{v=rx.recv()=>{let msg=match v{Ok(v)=>(*v).clone(),Err(broadcast::error::RecvError::Lagged(_))=>snapshot(&a).to_string(),Err(_)=>break};if socket.send(Message::Text(msg.into())).await.is_err(){break}},v=socket.recv()=>match v{Some(Ok(Message::Close(_)))|None|Some(Err(_))=>break,Some(Ok(Message::Ping(v)))=>{if socket.send(Message::Pong(v)).await.is_err(){break}},_=>{}}}}}
async fn security(State(a):State<App>,req:Request<axum::body::Body>,next:Next)->Response{
 let host=req.headers().get("host").and_then(|v|v.to_str().ok());if host!=Some("127.0.0.1:9899"){return StatusCode::FORBIDDEN.into_response()}
 if let Some(origin)=req.headers().get("origin"){if origin.to_str().ok()!=Some("http://127.0.0.1:9899"){return StatusCode::FORBIDDEN.into_response()}}
 if req.headers().get("sec-fetch-site").is_some_and(|v|v=="cross-site"){return StatusCode::FORBIDDEN.into_response()}
 if req.method()!=axum::http::Method::GET&&req.method()!=axum::http::Method::HEAD {
  if req.method()!=axum::http::Method::POST||!req.uri().path().starts_with("/api/manage/"){return StatusCode::METHOD_NOT_ALLOWED.into_response()}
  if req.headers().get("origin").and_then(|v|v.to_str().ok())!=Some("http://127.0.0.1:9899")||req.headers().get("x-sysmo-token").and_then(|v|v.to_str().ok())!=Some(a.management.token.as_str()){return StatusCode::FORBIDDEN.into_response()}
 }
 let api=req.uri().path().starts_with("/api/");let mut r=next.run(req).await;let h=r.headers_mut();h.insert("x-content-type-options","nosniff".parse().unwrap());h.insert("referrer-policy","no-referrer".parse().unwrap());h.insert("content-security-policy","default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self' ws://127.0.0.1:9899; frame-ancestors 'none'; base-uri 'none'".parse().unwrap());if api{h.insert("cache-control","no-store".parse().unwrap());}r
}
